### ISSUE TITLE
Fox can firefox diagonally through pokemon stadium

### ISSUE THREAD

**Issue by JohnnyUrosevic** [schmooblidon/meleelight#112] opened 2017-03-08 17:25 UTC
![capture](https://cloud.githubusercontent.com/assets/6700341/23715341/1f744b58-03e1-11e7-9923-5d355fb746e6.PNG)

Sorry if you know this already

**Comment by sheaf** [comment] 2017-03-08 17:27
Duplicate of #98, fixed by commit 669b2e6.

**Closed by sheaf** 2017-03-08 17:27 UTC
Labels: bug, duplicate
